networks:
  microservicios-net:
    driver: bridge

services:
  # --- BASES DE DATOS ---
  eureka:
    build: ./eureka
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - microservicios-net

  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - eureka
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    ports:
      - "8080:8080"
    networks:
      - microservicios-net

  db-productos:
    image: mysql
    environment:
      MYSQL_DATABASE: db_productos
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - microservicios-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  productos:
    build: ./productos
    container_name: productos
    depends_on:
      db-productos:
        condition: service_healthy
      eureka:
        condition: service_started
      categoriaspr:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-productos:3307/db_productos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - CATEGORIASPR_API_URL=http://categoriaspr:8083/api/v1
    networks:
      - microservicios-net

  db-clientes:
    image: mysql
    environment:
      MYSQL_DATABASE: db_clientes
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - microservicios-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  clientes:
    build: ./clientes
    container_name: clientes
    depends_on:
      db-clientes:
        condition: service_healthy
      eureka:
        condition: service_started
      categoriascl:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-clientes:3307/db_clientes
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - CATEGORIASCL_API_URL=http://categoriascl:8081/api/v1
    networks:
      - microservicios-net

  db-documento:
    image: mysql
    environment:
      MYSQL_DATABASE: db_documento
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - microservicios-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  documento:
    build: ./documento
    container_name: documento
    depends_on:
      db-documento:
        condition: service_healthy
      eureka:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-documento:3307/db_documento
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservicios-net

  db-categoriascl:
    image: mysql
    environment:
      MYSQL_DATABASE: db_categoriascl
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - microservicios-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  categoriascl:
    build: ./categoriacliente
    container_name: categoriascl
    depends_on:
      db-categoriascl:
        condition: service_healthy
      eureka:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-categoriascl:3307/db_categoriascl
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservicios-net

  db-categoriaspr:
    image: mysql
    environment:
      MYSQL_DATABASE: db_categoriaspr
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - microservicios-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  categoriaspr:
    build: ./categoriaproducto
    container_name: categoriaspr
    depends_on:
      db-categoriaspr:
        condition: service_healthy
      eureka:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-categoriaspr:3307/db_categoriaspr
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservicios-net

  db-pago:
    image: mysql
    environment:
      MYSQL_DATABASE: db_pago
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - microservicios-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  pago:
    build: ./pago
    container_name: pago
    depends_on:
      db-pago:
        condition: service_healthy
      eureka:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-pago:3307/db_pago
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservicios-net

  db-pedidos:
    image: mysql
    environment:
      MYSQL_DATABASE: db_pedidos
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - microservicios-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  pedidos:
    build: ./pedidos
    container_name: pedidos
    depends_on:
      db-pedidos:
        condition: service_healthy
      eureka:
        condition: service_started
      clientes:
        condition: service_started
      productos:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-pedidos:3307/db_pedidos
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - CLIENTES_API_URL=http://clientes:8089/api/v1
      - PRODUCTOS_API_URL=http://clientes:8082/api/v1
    networks:
      - microservicios-net

  db-stocks:
    image: mysql
    environment:
      MYSQL_DATABASE: db_stocks
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - microservicios-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  stocks:
    build: ./stocks
    container_name: stocks
    depends_on:
      db-stocks:
        condition: service_healthy
      eureka:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-stocks:3307/db_stocks
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservicios-net

  db-vendedores:
    image: mysql
    environment:
      MYSQL_DATABASE: db_vendedores
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - microservicios-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  vendedores:
    build: ./vendedores
    container_name: vendedores
    depends_on:
      db-vendedores:
        condition: service_healthy
      eureka:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-vendedores:3307/db_vendedores
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    networks:
      - microservicios-net

  db-venta:
    image: mysql
    environment:
      MYSQL_DATABASE: db_venta
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - microservicios-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  venta:
    build: ./venta
    container_name: venta
    depends_on:
      db-venta:
        condition: service_healthy
      eureka:
        condition: service_started
      clientes:
        condition: service_started
      pedidos:
        condition: service_started
      productos:
        condition: service_started
      vendedores:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-venta:3307/db_venta
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
      - CLIENTES_API_URL=http://clientes:8089/api/v1
      - PEDIDOS_API_URL=http://pedidos:8088/api/v1
      - PRODUCTOS_API_URL=http://clientes:8082/api/v1
      - VENDEDORES_API_URL=http://clientes:8085/api/v1
    networks:
      - microservicios-net