CREATE TABLE pedidos (
    id int NOT NULL AUTO_INCREMENT,
    pedido VARCHAR(255) NOT NULL,
    id_cliente INT DEFAULT NULL,
    id_producto INT DEFAULT NULL,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;