server.port=8080
spring.application.name=gateway
spring.cloud.gateway.routes[0].id=ruta-clientes
spring.cloud.gateway.routes[0].uri=lb://CLIENTES
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/**
spring.cloud.gateway.routes[1].id=ruta-productos
spring.cloud.gateway.routes[1].uri=lb://PRODUCTOS
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/**
spring.cloud.gateway.routes[2].id=ruta-categoriascl
spring.cloud.gateway.routes[2].uri=lb://CATEGORIASCLIENTE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/v1/**
spring.cloud.gateway.routes[3].id=ruta-categoriaspr
spring.cloud.gateway.routes[3].uri=lb://CATEGORIASPRODUCTO
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/**
spring.cloud.gateway.routes[4].id=ruta-documento
spring.cloud.gateway.routes[4].uri=lb://DOCUMENTO
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/v1/**
spring.cloud.gateway.routes[5].id=ruta-pago
spring.cloud.gateway.routes[5].uri=lb://PAGO
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/**
spring.cloud.gateway.routes[6].id=ruta-pedidos
spring.cloud.gateway.routes[6].uri=lb://PEDIDOS
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/v1/**
spring.cloud.gateway.routes[7].id=ruta-stocks
spring.cloud.gateway.routes[7].uri=lb://STOCKS
spring.cloud.gateway.routes[7].predicates[0]=Path=/api/v1/**
spring.cloud.gateway.routes[8].id=ruta-vendedores
spring.cloud.gateway.routes[8].uri=lb://VENDEDORES
spring.cloud.gateway.routes[8].predicates[0]=Path=/api/v1/**
spring.cloud.gateway.routes[9].id=ruta-venta
spring.cloud.gateway.routes[9].uri=lb://VENTA
spring.cloud.gateway.routes[9].predicates[0]=Path=/api/v1/**
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/





#YAML

#server:
    #port: 8080

#spring:
    #application:
        #name: gateway

#cloud:
    #gateway:
        #routes:
            #id: ruta-clientes
            #url: lb://CLIENTES
            #predicates:
                #- Path=/api/v1/clientes

#eureka
    #client:
        #service-url:
            #defaultZone: http://localhost:8761/eureka
